apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: java-guestbook-frontend
  labels:
    app: java-guestbook
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: java-guestbook
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: java-guestbook-frontend
        ports:
        - name: http-server
          containerPort: 8080
        - name: debug
          containerPort: 50005
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: java-guestbook-backend:8080
